

class dtNavMesh:
    def __init__(self) -> None: ...

    def init(self, params: "dtNavMeshParams") -> int: ...

    def getParams(self) -> "dtNavMeshParams": ...

    def getTileAt(self, arg0: int, arg1: int, arg2: int, /) -> "dtMeshTile": ...
